version: '3.8'

services:
  postgres:
    container_name: threads-db
    image: postgres
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgressql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=threads
      - POSTGRES_PASSWORD=threads
  
  threads-app-backend:
    container_name: threads-app
    build:
      context: .threads
      dockerfile: Dockerfile
    image: "pantherpaul/threads-app-backend"
    volumes:
      - .:/app
    env_file: ./.env
    ports:
      - 8000:8000
    environment:
      - NODE_ENV=development
    depends_on:
      - postgres
    command: >
      sh -c "npx prisma migrate dev --name basic-migration && 
            npm run dev"

volumes:
  postgres_data:
  node_modules:
    driver: local

networks:
  app-network:
    driver: bridge